<?php

namespace App;

use StoutLogic\AcfBuilder\FieldsBuilder;

$columns = new FieldsBuilder('columns');
$columns
    ->addTab('columns', ['placement' => 'left'])
        ->addFlexibleContent('columns', ['button_label' => __('Add columns', 'sage')])
            ->addLayout('heading', ['label' => __('Heading', 'sage')])
                ->addText('heading')
                ->addButtongroup('size')
                    ->addChoice('h1', __('Heading 1', 'sage'))
                    ->addChoice('h2', __('Heading 2', 'sage'))
                    ->addChoice('h3', __('Heading 3', 'sage'))
                    ->addChoice('h4', __('Heading 4', 'sage'))
            ->addLayout('divider', ['label' => __('Divider', 'sage')])
                ->addTruefalse('display_line', ['message' => __('Display Horizontal rule', 'sage')])
            ->addLayout('one_column_small', ['label' => __('Narrow column', 'sage')])
                ->addGroup('col_1')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
            ->addLayout('one_column', ['label' => __('1 column', 'sage')])
                ->addGroup('col_1')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
            ->addLayout('two_columns', ['label' => __('2 columns', 'sage')])
                ->addGroup('col_1')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
                ->addGroup('col_2')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
            ->addLayout('three_columns', ['label' => __('3 columns', 'sage')])
                ->addGroup('col_1')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
                ->addGroup('col_2')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
                ->addGroup('col_3')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
            ->addLayout('left_wide', ['label' => __('Left wide', 'sage')])
                ->addGroup('col_1')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
                ->addGroup('col_2')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
            ->addLayout('right_wide', ['label' => __('Right wide', 'sage')])
                ->addGroup('col_1')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
                ->addGroup('col_2')
                    ->addFields(get_field_partial('partials.column_content'))
                ->endGroup()
        ->endFlexibleContent()
    ->addTab('options')
        ->addFields(get_field_partial('partials.container_width'))
        ->addFields(get_field_partial('partials.bg_color'))
        ->addCheckbox('options', ['allow_custom' => 1, 'label' => __('Options', 'sage')])
            ->addChoice('mb', __('Margin bottom', 'sage'))
            ->addChoice('bg-img', __('Background image', 'sage'))
            ->addChoice('v-center', __('Vertical center', 'sage'))
            ->addChoice('text-center', __('Vertical center', 'sage'))
            ->addChoice('no-gutters', __('No gutters', 'sage'))
        ->addGroup('bg_image', ['label' => __('Background image', 'sage')])
            ->conditional('options', '==', 'bg-img')
            ->addFields(get_field_partial('partials.bg_img'))
        ->endGroup();

return $columns;
